---
name: Build

on:
  push:
    tags-ignore:
      - '**'
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install Tools
      run: |
        pushd "$(mktemp -d)"
        go get github.com/gordonklaus/ineffassign
        go get golang.org/x/lint/golint
        go get github.com/client9/misspell/cmd/misspell
        go get honnef.co/go/tools/cmd/staticcheck
        go get github.com/onsi/ginkgo/ginkgo github.com/onsi/gomega/...
        go get github.com/kevinburke/go-bindata/...
        popd

    - name: Get dependencies
      run: |
        make internal/img/font-hack.go

    - name: Build
      run: |
        go build ./...

    - name: Test
      run: |
        make test
