name: Release
on:
  push:
    tags:
      - "v*"

jobs:
  release-notary:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: goreleaser
        uses: docker://goreleaser/goreleaser:v0.149.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: release
